Input=input("Enter the input: ")
print("The input contains Character and Numbers",Input.isalnum())
print("The input contains Numbers",Input.isdigit())
print("The input contains character",Input.isalpha())
print("The input character is Lower",Input.islower())
print("The input character is Upper",Input.isupper())
